### ISSUE TITLE
Android Study Group - ToDo App

### ISSUE THREAD

**Issue by kathweaver** [kathweaver/MyToDoApp#1]
@CoderRed99 -- I have finished my todo app

**Comment by CoderRed99** [comment]
Got the issue alert! 

I didn't see the licecap gif file. Please check the emails for instructions and push it to Github and send me another alert when finished. If you sent it to me in an email, I can't animate it that way. You can enter it into a Readme.md file or just upload it as a Gif file into the main directory. If you have troubles getting it into the right folder, don't worry about it. Just let me know which folder it's in so I don't have to hunt for it. :) 

I'll review as as soon as I get back to my laptop.

**Comment by kathweaver** [comment]
Didn't see directions on how to do that.  I did create an animated gif and just added it to the repository.
